-- 1. TẠO CÁC ENUM TYPES
CREATE TYPE user_role AS ENUM ('student', 'organizer', 'staff');
CREATE TYPE workshop_status AS ENUM ('draft', 'published', 'cancelled', 'completed');
CREATE TYPE registration_status AS ENUM ('pending_payment', 'confirmed', 'checked_in', 'cancelled');
CREATE TYPE payment_status AS ENUM ('pending', 'success', 'failed', 'timeout');

-- 2. TẠO BẢNG NGƯỜI DÙNG (USERS)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) UNIQUE, -- Sẽ null nếu là organizer/staff
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    auth_id UUID UNIQUE REFERENCES auth.users(id)
);

-- 3. TẠO BẢNG PHÒNG (ROOMS)
CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    layout_image_url TEXT,
    capacity INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TẠO BẢNG WORKSHOP
CREATE TABLE workshops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    ai_summary TEXT, -- Lưu bản tóm tắt AI
    speaker_name VARCHAR(255) NOT NULL,
    room_id BIGINT REFERENCES rooms(id) ON DELETE RESTRICT,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time TIMESTAMP WITH TIME ZONE NOT NULL,
    is_free BOOLEAN DEFAULT TRUE,
    price DECIMAL(10, 2) DEFAULT 0,
    total_seats INT NOT NULL,
    available_seats INT NOT NULL,
    status workshop_status DEFAULT 'draft',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Ràng buộc: Không cho phép số chỗ còn lại bị âm
    CONSTRAINT check_positive_seats CHECK (available_seats >= 0)
);

-- 5. TẠO BẢNG ĐĂNG KÝ (REGISTRATIONS)
CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    workshop_id BIGINT REFERENCES workshops(id) ON DELETE CASCADE,
    status registration_status DEFAULT 'pending_payment',
    qr_code VARCHAR(255) UNIQUE NOT NULL,
    checked_in_at TIMESTAMP WITH TIME ZONE,
    offline_synced BOOLEAN DEFAULT FALSE, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    -- Đảm bảo 1 sinh viên chỉ đăng ký 1 workshop 1 lần
    UNIQUE(user_id, workshop_id)
);

-- 6. TẠO BẢNG THANH TOÁN (PAYMENTS)
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT REFERENCES registrations(id) ON DELETE CASCADE,
    amount DECIMAL(10, 2) NOT NULL,
    status payment_status DEFAULT 'pending',
    idempotency_key VARCHAR(255) UNIQUE NOT NULL, 
    gateway_transaction_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. TẠO BẢNG LOG CHECK-IN OFFLINE (OFFLINE_SYNC_LOGS)
CREATE TABLE offline_sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT REFERENCES registrations(id) ON DELETE CASCADE,
    staff_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    scanned_at TIMESTAMP WITH TIME ZONE NOT NULL, 
    synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- CẬP NHẬT LẠI STORED PROCEDURE CHO BIGINT
-- ==========================================
CREATE OR REPLACE FUNCTION register_workshop(
    p_user_id BIGINT, 
    p_workshop_id BIGINT, 
    p_qr_code VARCHAR
) RETURNS JSON AS $$
DECLARE
    v_available_seats INT;
    v_is_free BOOLEAN;
    v_registration_id BIGINT;
    v_status registration_status;
BEGIN
    -- 1. Lấy thông tin workshop và LOCK ROW bằng FOR UPDATE
    SELECT available_seats, is_free INTO v_available_seats, v_is_free
    FROM workshops
    WHERE id = p_workshop_id
    FOR UPDATE;

    -- 2. Kiểm tra chỗ trống
    IF v_available_seats <= 0 THEN
        RAISE EXCEPTION 'Workshop is fully booked';
    END IF;

    -- 3. Xác định trạng thái đăng ký
    IF v_is_free THEN
        v_status := 'confirmed';
    ELSE
        v_status := 'pending_payment';
    END IF;

    -- 4. Trừ số chỗ ngồi
    UPDATE workshops 
    SET available_seats = available_seats - 1 
    WHERE id = p_workshop_id;

    -- 5. Tạo bản ghi đăng ký
    INSERT INTO registrations (user_id, workshop_id, status, qr_code)
    VALUES (p_user_id, p_workshop_id, v_status, p_qr_code)
    RETURNING id INTO v_registration_id;

    -- 6. Trả về kết quả
    RETURN json_build_object(
        'success', true,
        'registration_id', v_registration_id,
        'status', v_status
    );
EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'User already registered for this workshop';
    WHEN OTHERS THEN
        RAISE EXCEPTION 'Registration failed: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;v